# 모든 페이지는 동적으로 생성한다. (SSR 방식)
# 그러므로 서브도메인으로의 접근은 리버스 프록시를 사용하여, Next.js로 연결한다.
# nginx 컨테이너는 SSR에 사용되는 정적 파일과, PHP-FPM에 사용되는 정적 파일을 서빙한다.
# 

services:
  # Next.js 서비스 (React 프론트엔드)
  nextjs:
    image: node:18 # Node.js 18 버전 이미지 사용
    container_name: nextjs # Docker 컨테이너 이름
    working_dir: /app # 컨테이너 내부의 작업 디렉터리 설정
    volumes:
      - ./frontend:/app # 로컬 frontend 폴더를 컨테이너의 /app에 마운트
      - /app/node_modules # node_modules는 컨테이너 내부에서만 관리 (/app 경로 내부에 node_modules가 있어도 마운트하지 않음.)
    ports:
      - "127.0.0.1:8445:3000" # 로컬호스트 8445번 포트를 컨테이너의 3000번 포트에 연결 (8445를 'log-analyzer' 서브도메인을 처리하는 프록시 주소로 설정함.)
      # - "127.0.0.1:3000" # 로컬호스트 3000번 포트를 컨테이너의 3000번 포트에 연결. (테스트용)
    command: /bin/sh -c "npm install && npm run dev" # 개발 서버 실행 명령
    environment:
      # 환경 변수 NODE_ENV로 실행 모드를 지정
      NODE_ENV: development # 현재는 개발 모드 활성화
      # NODE_ENV: production # 운영 모드 (활성화 시 주석 제거)
      # NODE_ENV: test       # 테스트 모드 (활성화 시 주석 제거)
    networks:
      - loganalyzer_net # 지정된 네트워크에 연결

  # PHP-FPM 서비스 (백엔드 API)
  php:
    image: php:8.1-fpm # PHP 8.1 FPM(FastCGI Process Manager) 이미지
    container_name: php-fpm # Docker 컨테이너 이름
    volumes:
      - ./backend:/var/www/html # 로컬 backend 폴더를 컨테이너의 /var/www/html에 마운트
      - /var/log/apache2:/php_data  # apache 로그를 컨테이너 내부에 마운트. (서비스시에는 환경변수로 대체.)
    expose:
      - "9000" # 내부적으로만 사용 (compose 파일 내부의 모든 파일은 동일 네트워크에서 실행됨. expose 옵션으로 동일 네트워크에서만 사용하는 포트 지정 가능.)
    networks:
      - loganalyzer_net # 지정된 네트워크에 연결

  # Nginx 서비스 (Reverse Proxy 및 정적 파일 서빙)
  nginx:
    image: nginx:alpine # 경량화된 Nginx 이미지 사용
    container_name: nginx # Docker 컨테이너 이름
    volumes:
      - ./nginx:/etc/nginx/conf.d # Nginx 커스텀 설정을 마운트
      #- ./frontend:/usr/share/nginx/html # 프론트엔드 정적 파일 서빙 경로 # 필요가 없을 것 같아 비활성화 해둠.
      - ./backend:/var/www/html # PHP 소스 저장 경로 (정적 웹루트)
    #ports:
    #  - "127.0.0.1:8080:80" # 로컬호스트 8080번 포트를 컨테이너의 80번 포트에 연결
    expose:
      - "80"  # 내부적으로만 80번 포트 노출함.
    depends_on:
      - nextjs # Nginx는 Next.js 서비스가 먼저 시작되어야 동작
      - php    # Nginx는 PHP 서비스가 필요
    networks:
      - loganalyzer_net # 지정된 네트워크에 연결

  # Ollama 서비스 (AI 모델 API)
  ollama:
    image: ollama/ollama # Ollama 공식 Docker 이미지 사용
    container_name: ollama # Docker 컨테이너 이름
    expose:
      - "11434" # Ollama API의 기본 포트
    networks:
      - loganalyzer_net # 지정된 네트워크에 연결

# 네트워크 설정
networks:
  loganalyzer_net:
    driver: bridge # 기본 브리지 네트워크 설정