import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import { ThemeProvider } from "./context/ThemeContext";
import LogoutButton from "./components/LogoutButton";
import DarkModeToggle from "./components/darkmodetoggle"; // 클라이언트 컴포넌트

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="en">
        <head>
          <meta charSet="utf-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <title>Log Analyzer</title>
        </head>
        <body className="bg-white text-black dark:bg-gray-900 dark:text-white">
          <div className="min-h-screen flex flex-col">
            <header className="bg-gray-200 text-white p-4 dark:bg-gray-800 flex justify-between items-center">
              <div>
                <h1 className="text-3xl font-bold">
                  <Link href="/" className="text-black dark:text-white">
                    🏠 Log Analyzer
                  </Link>
                </h1>
                <p className="text-lg text-black dark:text-white">
                  A tool that helps you to analyze your log files
                </p>
              </div>
              <div className="flex items-center space-x-4">
                <LogoutButton />
                <DarkModeToggle /> {/* 클라이언트 컴포넌트 */}
              </div>
            </header>
            <main className="flex flex-1">
              <nav className="w-1/5 bg-gray-200 p-4 dark:bg-gray-800">
                <ul className="space-y-2">
                  <div>
                    <h1 className="font-bold">MAIN MENU</h1>
                  </div>
                  <li>
                    <Link
                      href="/specific/main_menu/ai_search"
                      className="hover:bg-gray-300 dark:hover:bg-gray-700 px-2 py-1 rounded transition-colors"
                    >
                      🔎 AI Search
                    </Link>
                  </li>
                  <li>
                    <Link
                      href="/specific/main_menu/search"
                      className="hover:bg-gray-300 dark:hover:bg-gray-700 px-2 py-1 rounded transition-colors"
                    >
                      🔎 Search
                    </Link>
                  </li>
                  <li>
                    <Link
                      href="/specific/main_menu/suspicious_activity"
                      className="hover:bg-gray-300 dark:hover:bg-gray-700 px-2 py-1 rounded transition-colors"
                    >
                      🟡 Suspicious Activity
                    </Link>
                  </li>
                  <li>
                    <Link
                      href="/specific/main_menu/code_200"
                      className="hover:bg-gray-300 dark:hover:bg-gray-700 px-2 py-1 rounded transition-colors"
                    >
                      Status Codes
                    </Link>
                  </li>
                  <div>
                    <h1 className="font-bold">PREFERENCE</h1>
                  </div>
                  <li>
                    <Link
                      href="/specific/preference/settings"
                      className="hover:bg-gray-300 dark:hover:bg-gray-700 px-2 py-1 rounded transition-colors"
                    >
                      ⚙️ Settings
                    </Link>
                  </li>
                  <li>
                    <Link
                      href="/specific/preference/help_center"
                      className="hover:bg-gray-300 dark:hover:bg-gray-700 px-2 py-1 rounded transition-colors"
                    >
                      ❓ Help Center
                    </Link>
                  </li>
                </ul>
              </nav>
              <div className="w-4/5 p-4">
                <div className="bg-white shadow-md rounded p-4 dark:bg-gray-800">
                  {children}
                </div>
              </div>
            </main>
            <footer className="bg-gray-800 text-white p-4 text-center dark:bg-gray-900">
              &copy; 2024 Log Analyzer. All rights reserved.
            </footer>
          </div>
        </body>
      </html>
    </ThemeProvider>
  );
}
