server {
    listen 80;
    server_name localhost;

    root /var/www/html; # PHP 소스 코드의 루트 디렉터리
    index index.php;

    # PHP 파일 요청 처리
    location ~ \.php$ {
        include fastcgi_params; # 기본 FastCGI 파라미터 포함
        fastcgi_pass php-fpm:9000; # php-fpm 서비스의 9000번 포트와 연결
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; # 요청된 스크립트 경로 전달
        
    }

    # 404 처리 (PHP만 사용하므로 PHP 이외의 파일 요청에 대해 처리)
    location / {
        try_files $uri $uri/ /index.php?$query_string; # 없는 파일은 index.php로 전달
    }

    # 보안 헤더 추가
    add_header X-Frame-Options "DENY"; # 클릭재킹 방지
    add_header X-Content-Type-Options "nosniff"; # MIME 타입 강제 방지
    add_header X-XSS-Protection "1; mode=block"; # XSS 공격 방지
}
